from typing import Protocol

from app.domain.auth.entities import User


class AuthRepository(Protocol):
    def create_user(self, user: User) -> User: ...
    def get_user_by_id(self, user_id: str) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def get_user_by_username(self, username: str) -> User | None: ...
