from collections.abc import Mapping, Sequence
from typing import Protocol

from app.domain.ai.entities import AIProviderConfig, LearningPlanDraft


class AIRepository(Protocol):
    def list_provider_configs(self, user_id: str) -> Sequence[AIProviderConfig]: ...
    def get_provider_config(self, user_id: str, provider_id: str) -> AIProviderConfig | None: ...
    def get_default_provider_config(self, user_id: str) -> AIProviderConfig | None: ...
    def create_provider_config(self, config: AIProviderConfig) -> AIProviderConfig: ...
    def update_provider_config(
        self,
        user_id: str,
        provider_id: str,
        changes: Mapping[str, object],
    ) -> AIProviderConfig | None: ...
    def delete_provider_config(self, user_id: str, provider_id: str) -> bool: ...
    def set_default_provider_config(self, user_id: str, provider_id: str) -> AIProviderConfig | None: ...
    def create_plan_draft(self, draft: LearningPlanDraft) -> LearningPlanDraft: ...
