from collections.abc import Mapping, Sequence
from typing import Protocol

from app.domain.dashboard.entities import Goal, GoalTask, LearningItem, Note, Todo


class TodoRepository(Protocol):
    def list_todos(self) -> Sequence[Todo]: ...
    def create_todo(self, todo: Todo) -> Todo: ...
    def update_todo(self, todo_id: str, changes: Mapping[str, object]) -> Todo | None: ...
    def delete_todo(self, todo_id: str) -> bool: ...


class LearningRepository(Protocol):
    def list_learning_items(self) -> Sequence[LearningItem]: ...
    def create_learning_item(self, item: LearningItem) -> LearningItem: ...
    def update_learning_item(self, item_id: str, changes: Mapping[str, object]) -> LearningItem | None: ...
    def delete_learning_item(self, item_id: str) -> bool: ...


class NoteRepository(Protocol):
    def list_notes(self) -> Sequence[Note]: ...
    def create_note(self, note: Note) -> Note: ...
    def update_note(self, note_id: str, changes: Mapping[str, object]) -> Note | None: ...
    def delete_note(self, note_id: str) -> bool: ...


class GoalRepository(Protocol):
    def list_goals(self) -> Sequence[Goal]: ...
    def create_goal(self, goal: Goal) -> Goal: ...
    def update_goal(self, goal_id: str, changes: Mapping[str, object]) -> Goal | None: ...
    def delete_goal(self, goal_id: str) -> bool: ...
    def create_goal_task(self, task: GoalTask) -> GoalTask | None: ...
    def update_goal_task(self, goal_id: str, task_id: str, changes: Mapping[str, object]) -> GoalTask | None: ...
    def delete_goal_task(self, goal_id: str, task_id: str) -> bool: ...